services:
  application:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: application
    container_name: application
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_app
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app
    restart: unless-stopped

  mariadb:
    image: 'mariadb:11'
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'application-mariadb:/var/lib/mysql'
    networks:
      - laravel_app
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      retries: 3
      timeout: 5s
    restart: unless-stopped # Descomente essa linha para que o container seja reiniciado automaticamente
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'application-redis:/data'
    networks:
      - laravel_app
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    restart: unless-stopped # Descomente essa linha para que o container seja reiniciado automaticamente
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    #set the same network as the other services
    networks:
      - laravel_app
    restart: unless-stopped # Descomente essa linha para que o container seja reiniciado automaticamente
networks:
  laravel_app:
    driver: bridge
volumes:
  application-mariadb:
    driver: local
  application-redis:
    driver: local
